In [43]:
import pandas as pd
import polars as pl
import numpy as np
import xgboost as xgb
from src import exploration_cleaning_methods as ecm
from src import prediction_methods as pm

**Men**

In [44]:
m_train_df: pl.DataFrame = pl.read_parquet("../data/proccessed/m_train_data.parquet")
m_train_df.head(10)

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ … ┆ -0.040666    ┆ -0.014806    ┆ -0.007078    ┆ 0         │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ … ┆ -0.047807    ┆ -0.024097    ┆ 0.002589     ┆ 0         │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ … ┆ -0.008537    ┆ -0.001035    ┆ 0.017282     ┆ 0         │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ … ┆ -0.02873     ┆ 0.003899     ┆ 0.022644     ┆ 0         │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ … ┆ 0.037546     ┆ -0.04521     ┆ -0.031617    ┆ -13       │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ … ┆ -0.016964    ┆ 0.01076      ┆ -0.006101    ┆ -7        │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ … ┆ -0.000487    ┆ 0.047622     ┆ -0.024455    ┆ -5        │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ … ┆ -0.000502    ┆ -0.007881    ┆ 0.014252     ┆ -1        │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ … ┆ -0.044199    ┆ -0.053542    ┆ 0.032444     ┆ -9        │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ … ┆ 0.021938     ┆ -0.013491    ┆ -0.030793    ┆ 11        │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [45]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [46]:
m_prof_df: pl.DataFrame = ecm.create_team_season_profile(
    m_regular_season_detailed_lf.filter(pl.col("Season") == 2026)
).collect()

In [47]:
m_grid_df: pl.DataFrame = pm.create_carthesian_matchup_grid(
    m_regular_season_detailed_lf
    .filter(pl.col("Season") == 2026)
    .collect()
)

In [48]:
del m_regular_season_detailed_lf

In [49]:
m_infer_df: pl.DataFrame = (
    m_grid_df
    .join(
        m_prof_df, 
        left_on=["Season", "ATeamID"], 
        right_on=["Season", "TeamID"], 
        how="left"
    )
    .join(
        m_prof_df, 
        left_on=["Season", "BTeamID"], 
        right_on=["Season", "TeamID"], 
        how="left", 
        suffix="_B"
))

In [50]:
base_cols: list[str] = [
    "TeamScore", "OpponentScore", "WinRatio", "Location", "TeamPOS", 
    "OpponentPOS", "OffEfficiency", "DefEfficiency", "TeamEFG", 
    "OpponentEFG", "TurnoverRate"
]

for col in base_cols:
    m_infer_df = m_infer_df.with_columns((pl.col(col) - pl.col(f"{col}_B")).alias(f"{col}_Diff"))

In [51]:
del m_grid_df, m_prof_df

In [52]:
m_model: xgb.Booster = pm.generate_model(m_train_df)
feat_cols: list[str] = [f"{col}_Diff" for col in base_cols]
m_sub: pl.DataFrame = pm.predict_and_create_submission_data(m_model, feat_cols, m_infer_df)
m_sub.head(10)

shape: (10, 2)
┌────────────────┬──────────┐
│ ID             ┆ Pred     │
│ ---            ┆ ---      │
│ str            ┆ f32      │
╞════════════════╪══════════╡
│ 2026_1462_1477 ┆ 0.943773 │
│ 2026_1462_1465 ┆ 0.408792 │
│ 2026_1462_1471 ┆ 0.526872 │
│ 2026_1462_1480 ┆ 0.866596 │
│ 2026_1462_1474 ┆ 0.537494 │
│ 2026_1462_1468 ┆ 0.870436 │
│ 2026_1462_1469 ┆ 0.782557 │
│ 2026_1462_1475 ┆ 0.789253 │
│ 2026_1462_1481 ┆ 0.825404 │
│ 2026_1462_1472 ┆ 0.235672 │
└────────────────┴──────────┘

**Women**

In [53]:
w_train_df: pl.DataFrame = pl.read_parquet("../data/proccessed/w_train_data.parquet")
w_train_df.head(10)

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ … ┆ -0.065267    ┆ -0.022153    ┆ 0.002366     ┆ 3         │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ … ┆ 0.06781      ┆ -0.053646    ┆ -0.008088    ┆ -13       │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ … ┆ 0.002632     ┆ 0.000894     ┆ 0.012675     ┆ -9        │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ … ┆ 0.010844     ┆ -0.037637    ┆ 0.030525     ┆ -3        │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ … ┆ 0.028656     ┆ 0.038958     ┆ -0.047683    ┆ 1         │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ … ┆ -0.018015    ┆ -0.041011    ┆ 0.009153     ┆ -9        │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ … ┆ 0.030676     ┆ 0.016624     ┆ 0.003185     ┆ 5         │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ … ┆ 0.03694      ┆ 0.048403     ┆ -0.012815    ┆ -11       │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ … ┆ 0.001469     ┆ -0.000361    ┆ -0.013834    ┆ -13       │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ … ┆ -0.047435    ┆ -0.002718    ┆ 0.041146     ┆ 5         │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [54]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect

In [55]:
w_prof_df: pl.DataFrame = ecm.create_team_season_profile(
    w_regular_season_detailed_lf.filter(pl.col("Season") == 2026)
).collect()

In [56]:
w_grid_df: pl.DataFrame = pm.create_carthesian_matchup_grid(
    w_regular_season_detailed_lf
    .filter(pl.col("Season") == 2026)
    .collect()
)

In [57]:
del w_regular_season_detailed_lf

In [58]:
w_infer_df: pl.DataFrame = (
    w_grid_df
    .join(
        w_prof_df, 
        left_on=["Season", "ATeamID"], 
        right_on=["Season", "TeamID"], 
        how="left"
    )
    .join(
        w_prof_df, 
        left_on=["Season", "BTeamID"], 
        right_on=["Season", "TeamID"], 
        how="left", 
        suffix="_B"
))

In [59]:
base_cols: list[str] = [
    "TeamScore", "OpponentScore", "WinRatio", "Location", "TeamPOS", 
    "OpponentPOS", "OffEfficiency", "DefEfficiency", "TeamEFG", 
    "OpponentEFG", "TurnoverRate"
]

for col in base_cols:
    w_infer_df = w_infer_df.with_columns((pl.col(col) - pl.col(f"{col}_B")).alias(f"{col}_Diff"))

In [60]:
del w_grid_df, w_prof_df

In [61]:
w_model: xgb.Booster = pm.generate_model(w_train_df)
feat_cols: list[str] = [f"{col}_Diff" for col in base_cols]
w_sub: pl.DataFrame = pm.predict_and_create_submission_data(w_model, feat_cols, w_infer_df)
w_sub.head(10)

shape: (10, 2)
┌────────────────┬──────────┐
│ ID             ┆ Pred     │
│ ---            ┆ ---      │
│ str            ┆ f32      │
╞════════════════╪══════════╡
│ 2026_3177_3278 ┆ 0.030071 │
│ 2026_3177_3430 ┆ 0.58564  │
│ 2026_3177_3180 ┆ 0.241172 │
│ 2026_3177_3308 ┆ 0.85308  │
│ 2026_3177_3290 ┆ 0.870111 │
│ 2026_3177_3299 ┆ 0.847909 │
│ 2026_3177_3448 ┆ 0.033302 │
│ 2026_3177_3427 ┆ 0.457441 │
│ 2026_3177_3454 ┆ 0.408166 │
│ 2026_3177_3317 ┆ 0.118201 │
└────────────────┴──────────┘